name: Deploy Static Blog to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}

          # 要在服务器上执行的脚本
          script: |
            # 加上 set -e，确保任何命令失败时脚本都会立即退出
            set -e

            # 1. 进入你的项目源码目录 (请替换成你服务器上的实际路径)
            cd /srv/my-blog-source

            # 2. 从 GitHub 拉取最新的代码
            echo "Pulling latest code from GitHub..."
            git pull origin main

            # 3. 安装 pnpm 依赖
            echo "Installing dependencies..."
            pnpm install

            # 4. 执行构建命令
            echo "Building the static site..."
            pnpm run build

            # 5. 清理旧的网站文件 (非常重要，防止留下已删除的旧文件)
            echo "Cleaning up old files in /var/www/my-blog..."
            rm -rf /var/www/my-blog/*

            # 6. 拷贝构建产物到网站根目录
            # 注意 `out/.` 的用法，它会拷贝 out 目录下的所有内容，而不是 out 目录本身
            echo "Copying new build files to web root..."
            cp -r out/. /var/www/my-blog/

            # 只有在以上所有步骤都成功后，才会执行到这里
            echo "Deployment successful!"