name: Build and Deploy Next.js to Server

# 触发条件：当有代码 push 到 main 分支时
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 虚拟机

    steps:
      # 步骤 1: 检出你的代码
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 步骤 2 (新增): 安装 pnpm
      # 这是最关键的修复步骤，必须在 setup-node 之前
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 # 或者您正在使用的 pnpm 版本

      # 步骤 3: 设置 Node.js 环境
      # 它会自动找到由上一步安装的 pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm' # 这里的 'pnpm' 缓存设置是正确的

      # 步骤 4: 安装依赖 
      - name: Install Dependencies
        run: pnpm install 

      # 步骤 5: 构建静态站点
      - name: Build Static Site
        run: pnpm run build

      # 步骤 6: 使用 rsync 部署到服务器
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          # 源目录：构建产物 out/ 文件夹下的所有内容
          SOURCE: "out/"
          TARGET: ${{ secrets.DEPLOY_PATH }} # 
          EXCLUDE: "/.git/, /.github/"
          ARGS: "-e 'ssh -p ${ secrets.SSH_PORT } -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no' -rltgoDzv --delete"